spring:
  application:
    name: account-service
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://localhost:3306/accounts?useSsl=false
    username: admin
    password: uD)19Jbs=#cVa?+
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8080/ConfigServer/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/EurekaServer/

info:
  app:
    name: account-service
    description: SK Bank Account Application
    version: 25.1.0

datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

