build:
  version: 25.1.0

card-service:
  message: Welcome to SK Bank Card Related APIs
  contactDetails:
    name: Somukumar Ekambaram
    email: somukumar.ekambaram@gmail.com
  onCallSupport:
    - +91 (866) 805-4236