server:
  port: 8083
  servlet:
    context-path: /CardService

spring:
  application:
    name: card-service
  profiles:
    active: default

  datasource:
    cards:
      url: jdbc:mysql://localhost:3306/cards?useSsl=false
      username: admin
      password: uD)19Jbs=#cVa?+
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8080/ConfigServer/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/EurekaServer/eureka

info:
  app:
    name: card-service
    description: SK Bank Card Application
    version: 25.1.0

datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

#springdoc:
#  api-docs:
#    path: /AccountService/v3/api-docs
#  swagger-ui:
#    path: /AccountService/swagger-ui.html

